import { writable, get } from 'svelte/store';
import type { Params } from '$lib/utils/types';

export const params = writable<Params>({
  min_frequency: 75,
  max_frequency: 600,
  time_resolution_ms: 5,
  frequency_tolerance_cents: 100,
  min_note_duration_ms: 100,
  max_gap_to_bridge_ms: 500,
  silence_threshold_db: -30,
  transition_ramp_ms: 100,
  gap_threshold_ms: 150,
  correction_strength: 90,
  midi_threshold_cents: 80,
  autocorrect_smoothing: 0,
  smoothing_threshold_cents: 0,
  smoothing_threshold_ms: 0,
  smooth_curve: 1.0,
  segment_padding_ms: 100,
  segment_crossfade_ms: 10,
  segment_crop_ms: 50,
  segment_neighbor_count: 1,
  segment_auto_process: true,
  max_note_stretch: 200,
  max_note_compress: 50,
  max_gap_stretch: 300,
  max_gap_compress: 50,
  rb: {
    command: 'rubberband-r3',
    crisp: 3,
    formant: true,
    pitch_hq: true,
    window_long: true,
    smoothing: true,
    enable_pitchmap: true,
    enable_timemap: true,
  },
  pitch_engine: 'psola',
  sms: {
    max_harmonics: 60,
    peak_threshold: -80,
    stochastic_factor: 0.05,
    timbre_preserve: true,
    hop_size: 128,
    synth_fft_size: 2048,
    f0_error_threshold: 5.0,
    harm_dev_slope: 0.01,
    min_sine_dur: 0.02,
    residual_level: 1.0,
  },
  psola: {
    min_pitch: 75,
    max_pitch: 600,
    time_step: 0.01,
    resynthesis_method: 'overlap_add',
    pitch_point_step: 1,
    pitch_smooth_window_ms: 0,
    max_shift_semitones: 12,
  },
  voicing_threshold: 0.75,
  time_match_max_distance_ms: 500,
  time_match_strength: 100,
  time_match_max_change_ms: 200,
  cluster_padding_ms: 300,
  fd_psola: {
    fft_size: 2048,
    window_type: 'kaiser',
    formant_preservation: true,
    formant_method: 'cepstral',
    envelope_order: 30,
    overlap_factor: 4,
    phase_mode: 'pitch_sync',
    min_pitch: 75,
    max_pitch: 600,
    kaiser_beta: 8.0,
  },
});

export function getAllParams(): Params {
  return get(params);
}
